version: '3'
services:
  authservice:
    image: auth-service
    build:
      context: ${PROJECT_PATH}/auth-service
      dockerfile: ${PROJECT_PATH}/auth-service/Dockerfile
    ports:
      - "8089:8089"
    restart: always
    depends_on:
      - mypostgres
    environment:
      - SPRING_DATASOURCE_URL=${DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - telecounselor-app-db-network    
       
  userservice:
    image: user-service
    build:
      context: ${PROJECT_PATH}/user-service
      dockerfile: ${PROJECT_PATH}/user-service/Dockerfile
    ports:
      - "8085:8085"
    restart: always
    depends_on:
      - mypostgres
    environment:
      - SPRING_DATASOURCE_URL=${DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - telecounselor-app-db-network